GET http://localhost:3001/api/currency

###

GET http://localhost:3001/api/country

###

POST http://localhost:3001/api/currency
Content-Type: application/json

{
    
    "currencyCode":"EU",
    "countryId":5,
    "conversionRate":0.68
}

###
DELETE http://localhost:3001/api/currency/EU

### 
PUT  http://localhost:3001/api/currency/EUR/0.7