name: Production deployment pipeline
on:
  push:
    branches:
      - production
jobs:
  Client_test-pipeline:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Installing dependencies
        run: npm install

      - name: Install Jest
        run: npm install jest
        
      - name: Run frontend tests
        run: npm run test
      
      - name: Run client hook
        run: curl ${{ secrets.CLIENT_DEPLOYMENT_HOOK }} 


        

  Server-test-pipeline:
    runs-on: ubuntu-latest
    env:
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_USER: ${{secrets.DB_USER}}
    defaults: 
      run:
        working-directory: ./server
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          
        - name: Installing dependencies
          run: npm install

        - name: Run backend tests
          run: npm run test

        - name: Run servrt hook
          run: curl ${{ secrets.SERVER_DEPLOYMENT_HOOK }}

          

        

        

      
    
  
